# Problem 30: Write a python function parse_csv to parse csv (comma separated values) files.

def parse_cv():
    r=[]
    f=open('f1.txt','r')
    for line in f:
        line=line.strip()
        new=line.split(",")
        r.append(new)
    return r
print(parse_cv())

# Problem 32: Write a function mutate to compute all words generated by a single mutation on a given word. A mutation is defined as inserting a character, deleting a character, replacing a character, or swapping 2 consecutive characters in a string. For simplicity consider only letters from a to z.

def mutate(numbers):

    for i in range(len(numbers)):
        numbers[i]=numbers[i]*2
num = [1, 2, 3]
mutate(num)
print(num)

